source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '11.0'

target 'HSVColorPicker' do
  pod "HSVColorPicker", :path => "../"
end

target 'Tests' do
  pod "HSVColorPicker", :path => "../"

  pod 'Specta', '~> 0.2.1'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
end
